---
title: "Data Wrangling II: Reading Data from the Web"
author: "Diana Hernandez"
date: "2023-10-12"
output: github_document
---

Load necessary libraries

```{r}
library(tidyverse)
library(rvest)
library(httr)
```


```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = 
  read_html(nsduh_url)
```

`first()` gives us first one in a list. `slice()` can remove rows.

```{r}
marj_use_df =
nsduh_html |>
  html_table() |>
  first() |>
  slice(-1)
```

# CSS Selectors

Import Star Wars

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

# Use Selector Gadget on the website...

```{r}
swm_title_vec = 
  swm_html|>
    html_elements(".lister-item-header a") |>
    html_text()

swm_gross_vec = 
  swm_html|>
  html_elements(".text-muted .ghost~ .text-muted+ span") |>
    html_text()

swm_df = tibble(
  title = swm_title_vec,
  gross = swm_gross_vec
)
```

# Using an API

Get water data from NYC.

`content()` gives the data. `parsed` will help organize. Use `GET()` for APIs.

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
```

BRFSS data

```{r}
brfss_smart2010 = 
  GET("https://data.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content("parsed")
```

Pokemon data

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") |>
  content()
```

